version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Tehran
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      production-patches:
        dependency-type: production
        update-types:
          - patch
      development-patches:
        dependency-type: development
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Asia/Tehran
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
