version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Tehran
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
    groups:
      workspace-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "06:30"
      timezone: Asia/Tehran
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "chore(deps)"
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
    groups:
      actions-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
